packages:
  - '.'
  - 'score-relay'

allowBuilds:
  esbuild: true

ignoredBuiltDependencies:
  - esbuild
overrides:
  '@tennisvisuals/scoring-visualizations': link:../scoringVisualizations
  courthive-components: link:../courthive-components
  tods-competition-factory: link:../factory
